INSERT INTO director VALUES(1, 'Stanley Kubrick');
INSERT INTO director VALUES(2, 'Francis Ford Coppola');
INSERT INTO director VALUES(3, 'Orson Welles');
INSERT INTO director VALUES(4, 'Chantal Akerman');
INSERT INTO director VALUES(5, 'Steven Spielberg');
INSERT INTO director VALUES(6, 'Federico Fellini');
INSERT INTO director VALUES(7, 'Akira Kurosawa');
INSERT INTO director VALUES(8, 'Kar-Wai Wong');
INSERT INTO director VALUES(9, 'Paul Thomas Anderson');
INSERT INTO director VALUES(10, 'Stanley Donen, Gene Kelly');
INSERT INTO director VALUES(11, 'Martin Scorsese');
INSERT INTO director VALUES(12, 'Alfred Hitchcock');
INSERT INTO director VALUES(13, 'David Lynch');
INSERT INTO director VALUES(14, 'Vittorio De Sica');
INSERT INTO director VALUES(15, 'Christopher Nolan');
INSERT INTO director VALUES(16, 'Charles Chaplin');
INSERT INTO director VALUES(17, 'Jean Renoir');
INSERT INTO director VALUES(18, 'Howard Hawks');
INSERT INTO director VALUES(19, 'Michael Powell, Emeric Pressburger');
INSERT INTO director VALUES(20, 'Claire Denis');
INSERT INTO director VALUES(21, 'John Ford');
INSERT INTO director VALUES(22, 'Ingmar Bergman');
INSERT INTO director VALUES(23, 'Spike Lee');
INSERT INTO director VALUES(24, 'Billy Wilder');
INSERT INTO director VALUES(25, 'François Truffaut');
INSERT INTO director VALUES(26, 'George Lucas');
INSERT INTO director VALUES(27, 'Carl Theodor Dreyer');
INSERT INTO director VALUES(28, 'Sergio Leone');
INSERT INTO director VALUES(29, 'Ridley Scott');
INSERT INTO director VALUES(30, 'Yasujirô Ozu');
INSERT INTO director VALUES(31, 'Quentin Tarantino');
INSERT INTO director VALUES(32, 'Peter Weir');
INSERT INTO director VALUES(33, 'David Lean');
INSERT INTO director VALUES(34, 'Kenji Mizoguchi');
INSERT INTO director VALUES(35, 'Andrei Tarkovsky');
INSERT INTO director VALUES(36, 'Jacques Demy');
INSERT INTO director VALUES(37, 'Roman Polanski');
INSERT INTO director VALUES(38, 'Sofia Coppola');
INSERT INTO director VALUES(39, 'Hayao Miyazaki');
INSERT INTO director VALUES(40, 'George A. Romero');
INSERT INTO director VALUES(41, 'Sergei Eisenstein');
INSERT INTO director VALUES(42, 'Jean-Luc Godard');
INSERT INTO director VALUES(43, 'Fritz Lang');
INSERT INTO director VALUES(44, 'Stephen Norrington');
INSERT INTO director VALUES(45, 'Rainer Werner Fassbinder');
INSERT INTO director VALUES(46, 'Roberto Rossellini');
INSERT INTO director VALUES(47, 'F.W. Murnau');
INSERT INTO director VALUES(48, 'Jim Abrahams, David Zucker, Jerry Zucker');
INSERT INTO director VALUES(49, 'Jonathan Glazer');
INSERT INTO director VALUES(50, 'George Miller');
INSERT INTO director VALUES(51, 'Ang Lee');
INSERT INTO director VALUES(52, 'Leo McCarey');
INSERT INTO director VALUES(53, 'Daniel Myrick, Eduardo Sánchez');
INSERT INTO director VALUES(54, 'Clyde Bruckman, Buster Keaton');
INSERT INTO director VALUES(55, 'Michel Gondry');
INSERT INTO director VALUES(56, 'Tobe Hooper');
INSERT INTO director VALUES(57, 'Elem Klimov');
INSERT INTO director VALUES(58, 'Michael Mann');
INSERT INTO director VALUES(59, 'John Lasseter');
INSERT INTO director VALUES(60, 'Charles Burnett');
INSERT INTO director VALUES(61, 'John Cassavetes');
INSERT INTO director VALUES(62, 'Woody Allen');
INSERT INTO director VALUES(63, 'John Huston');
INSERT INTO director VALUES(64, 'Rob Reiner');
INSERT INTO director VALUES(65, 'Frank Capra');
INSERT INTO director VALUES(66, 'John McTiernan');
INSERT INTO director VALUES(67, 'Bernardo Bertolucci');
INSERT INTO director VALUES(68, 'John Carpenter');
INSERT INTO director VALUES(69, 'Julie Dash');
INSERT INTO director VALUES(70, 'Werner Herzog');
INSERT INTO director VALUES(71, 'Gillo Pontecorvo');
INSERT INTO director VALUES(72, 'Pedro Almodóvar');
INSERT INTO director VALUES(73, 'Richard Linklater');
INSERT INTO director VALUES(74, 'Luis Buñuel');
INSERT INTO director VALUES(75, 'David Yates');
INSERT INTO director VALUES(76, 'Alexander Mackendrick');
INSERT INTO director VALUES(77, 'Robert Wiene');
INSERT INTO director VALUES(78, 'Robert Altman');
INSERT INTO director VALUES(79, 'Arthur Penn');
INSERT INTO director VALUES(80, 'Jordan Peele');

INSERT INTO genre VALUES(1, 'Adventure');
INSERT INTO genre VALUES(2, 'Sci-Fi');
INSERT INTO genre VALUES(3, 'Crime');
INSERT INTO genre VALUES(4, 'Drama');
INSERT INTO genre VALUES(5, 'Mystery');
INSERT INTO genre VALUES(6, 'Action');
INSERT INTO genre VALUES(7, 'Comedy');
INSERT INTO genre VALUES(8, 'Romance');
INSERT INTO genre VALUES(9, 'Musical');
INSERT INTO genre VALUES(10, 'Biography');
INSERT INTO genre VALUES(11, 'Thriller');
INSERT INTO genre VALUES(12, 'War');
INSERT INTO genre VALUES(13, 'Music');
INSERT INTO genre VALUES(14, 'Western');
INSERT INTO genre VALUES(15, 'Film-Noir');
INSERT INTO genre VALUES(16, 'Fantasy');
INSERT INTO genre VALUES(17, 'History');
INSERT INTO genre VALUES(18, 'Horror');
INSERT INTO genre VALUES(19, 'Animation');
INSERT INTO genre VALUES(20, 'Family');
INSERT INTO genre VALUES(21, 'Sport');

INSERT INTO movie VALUES(1, '2001: A Space Odyssey', 1968, 'The Monoliths push humanity to reach for the stars; after their discovery in Africa generations ago, the mysterious objects lead mankind on an awesome journey to Jupiter, with the help of H.A.L. 9000: the world''s greatest supercomput', 'poster.jpg', 149, 1);
INSERT INTO movie VALUES(2, 'The Godfather', 1972, 'The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.', 'poster.jpg', 175, 2);
INSERT INTO movie VALUES(3, 'Citizen Kane', 1941, 'Following the death of publishing tycoon Charles Foster Kane, reporters scramble to uncover the meaning of his final utterance: ''Rosebud.''', 'poster.jpg', 119, 3);
INSERT INTO movie VALUES(4, 'Jeanne Dielman, 23, quai du commerce, 1080 Bruxelles', 1975, 'A lonely widowed housewife does her daily chores, takes care of her apartment where she lives with her teenage son, and turns the occasional trick to make ends meet. However, something happens that changes her safe routine.', 'poster.jpg', 202, 4);
INSERT INTO movie VALUES(5, 'Indiana Jones and the Raiders of the Lost Ark', 1981, 'In 1936, archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before Adolf Hitler''s Nazis can obtain its awesome powers.', 'poster.jpg', 115, 5);
INSERT INTO movie VALUES(6, 'La Dolce Vita', 1960, 'A series of stories following a week in the life of a philandering tabloid journalist living in Rome.', 'poster.jpg', 174, 6);
INSERT INTO movie VALUES(7, 'Seven Samurai', 1954, 'A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.', 'poster.jpg', 207, 7);
INSERT INTO movie VALUES(8, 'In the Mood for Love', 2000, 'Two neighbors form a strong bond after both suspect extramarital activities of their spouses. However, they agree to keep their bond platonic so as not to commit similar wrongs.', 'poster.jpg', 98, 8);
INSERT INTO movie VALUES(9, 'There Will Be Blood', 2007, 'A story of family, religion, hatred, oil and madness, focusing on a turn-of-the-century prospector in the early days of the business.', 'poster.jpg', 158, 9);
INSERT INTO movie VALUES(10, 'Singin'' in the Rain', 1952, 'A silent film star falls for a chorus girl just as he and his delusionally jealous screen partner are trying to make the difficult transition to talking pictures in 1920s Hollywood.', 'poster.jpg', 103, 10);
INSERT INTO movie VALUES(11, 'Goodfellas', 1990, 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.', 'poster.jpg', 145, 11);
INSERT INTO movie VALUES(12, 'North by Northwest', 1959, 'A New York City advertising executive goes on the run after being mistaken for a government agent by a group of foreign spies, and falls for a woman whose loyalties he begins to doubt.', 'poster.jpg', 136, 12);
INSERT INTO movie VALUES(13, 'Mulholland Drive', 2001, 'After a car wreck on the winding Mulholland Drive renders a woman amnesiac, she and a perky Hollywood-hopeful search for clues and answers across Los Angeles in a twisting venture beyond dreams and reality.', 'poster.jpg', 147, 13);
INSERT INTO movie VALUES(14, 'Bicycle Thieves', 1948, 'In post-war Italy, a working-class man''s bicycle is stolen, endangering his efforts to find work. He and his son set out to find it.', 'poster.jpg', 89, 14);
INSERT INTO movie VALUES(15, 'The Dark Knight', 2008, 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.', 'poster.jpg', 152, 15);
INSERT INTO movie VALUES(16, 'City Lights', 1931, 'With the aid of a wealthy erratic tippler, a dewy-eyed tramp who has fallen in love with a sightless flower girl accumulates money to be able to help her medically.', 'poster.jpg', 87, 16);
INSERT INTO movie VALUES(17, 'The Grand Illusion', 1937, 'During WWI, two French soldiers are captured and imprisoned in a German P.O.W. camp. Several escape attempts follow until they are eventually sent to a seemingly inescapable fortress.', 'poster.jpg', 113, 17);
INSERT INTO movie VALUES(18, 'His Girl Friday', 1940, 'A newspaper editor uses every trick in the book to keep his ace reporter ex-wife from remarrying.', 'poster.jpg', 92, 18);
INSERT INTO movie VALUES(19, 'The Red Shoes', 1948, 'A young ballet dancer is torn between the man she loves and her pursuit to become a prima ballerina.', 'poster.jpg', 135, 19);
INSERT INTO movie VALUES(20, 'Vertigo', 1958, 'A former San Francisco police detective juggles wrestling with his personal demons and becoming obsessed with the hauntingly beautiful woman he has been hired to trail, who may be deeply disturbed.', 'poster.jpg', 128, 12);
INSERT INTO movie VALUES(21, 'Beau travail', 1999, 'This film focuses on an ex-Foreign Legion officer as he recalls his once glorious life, leading troops in Djibouti.', 'poster.jpg', 92, 20);
INSERT INTO movie VALUES(22, 'The Searchers', 1956, 'An American Civil War veteran embarks on a years-long journey to rescue his niece from the Comanches after the rest of his brother''s family is massacred in a raid on their Texas farm.', 'poster.jpg', 119, 21);
INSERT INTO movie VALUES(23, 'Persona', 1966, 'A nurse is put in charge of a mute actress and finds that their personae are melding together.', 'poster.jpg', 83, 22);
INSERT INTO movie VALUES(24, 'Do the Right Thing', 1989, 'On the hottest day of the year on a street in the Bedford-Stuyvesant section of Brooklyn, everyone''s hate and bigotry smolders and builds until it explodes into violence.', 'poster.jpg', 120, 23);
INSERT INTO movie VALUES(25, 'Rashomon', 1950, 'The rape of a bride and the murder of her samurai husband are recalled from the perspectives of a bandit, the bride, the samurai''s ghost and a woodcutter.', 'poster.jpg', 88, 7);
INSERT INTO movie VALUES(26, 'The Rules of the Game', 1939, 'A bourgeois life in France at the onset of World War II, as the rich and their poor servants meet up at a French chateau.', 'poster.jpg', 110, 17);
INSERT INTO movie VALUES(27, 'Jaws', 1975, 'When a killer shark unleashes chaos on a beach community off Long Island, it''s up to a local sheriff, a marine biologist, and an old seafarer to hunt the beast down.', 'poster.jpg', 124, 5);
INSERT INTO movie VALUES(28, 'Double Indemnity', 1944, 'A Los Angeles insurance representative lets an alluring housewife seduce him into a scheme of insurance fraud and murder that arouses the suspicion of his colleague, an insurance investigator.', 'poster.jpg', 107, 24);
INSERT INTO movie VALUES(29, 'The 400 Blows', 1959, 'A young boy, left without attention, delves into a life of petty crime.', 'poster.jpg', 99, 25);
INSERT INTO movie VALUES(30, 'Star Wars', 1977, 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire''s world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vad', 'poster.jpg', 121, 26);
INSERT INTO movie VALUES(31, 'The Passion of Joan of Arc', 1928, 'In 1431, Jeanne d''Arc is placed on trial on charges of heresy. The ecclesiastical jurists attempt to force Jeanne to recant her claims of holy visions.', 'poster.jpg', 114, 27);
INSERT INTO movie VALUES(32, 'Once Upon a Time in the West', 1968, 'A mysterious stranger with a harmonica joins forces with a notorious desperado to protect a beautiful widow from a ruthless assassin working for the railroad.', 'poster.jpg', 165, 28);
INSERT INTO movie VALUES(33, 'Alien', 1979, 'The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission.', 'poster.jpg', 117, 29);
INSERT INTO movie VALUES(34, 'Tokyo Story', 1953, 'An old couple visit their children and grandchildren in the city, but receive little attention.', 'poster.jpg', 136, 30);
INSERT INTO movie VALUES(35, 'Pulp Fiction', 1994, 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'poster.jpg', 154, 31);
INSERT INTO movie VALUES(36, 'The Truman Show', 1998, 'An insurance salesman discovers his whole life is actually a reality TV show.', 'poster.jpg', 103, 32);
INSERT INTO movie VALUES(37, 'Lawrence of Arabia', 1962, 'The story of T.E. Lawrence, the English officer who successfully united and led the diverse, often warring, Arab tribes during World War I in order to fight the Turks.', 'poster.jpg', 218, 33);
INSERT INTO movie VALUES(38, 'Psycho', 1960, 'A Phoenix secretary embezzles $40,000 from her employer''s client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother.', 'poster.jpg', 109, 12);
INSERT INTO movie VALUES(39, 'Sansho the Bailiff', 1954, 'In medieval Japan, a compassionate governor is sent into exile. His wife and children try to join him, but are separated, and the children grow up amid suffering and oppression.', 'poster.jpg', 124, 34);
INSERT INTO movie VALUES(40, 'Andrei Rublev', 1966, 'The life, times and afflictions of the fifteenth-century Russian iconographer St. Andrei Rublev.', 'poster.jpg', 205, 35);
INSERT INTO movie VALUES(41, 'The Umbrellas of Cherbourg', 1964, 'A young woman separated from her lover by war faces a life-altering decision.', 'poster.jpg', 91, 36);
INSERT INTO movie VALUES(42, 'Chinatown', 1974, 'A private detective hired to expose an adulterer in 1930s Los Angeles finds himself caught up in a web of deceit, corruption, and murder.', 'poster.jpg', 130, 37);
INSERT INTO movie VALUES(43, 'The Seventh Seal', 1957, 'A knight returning to Sweden after the Crusades seeks answers about life, death, and the existence of God as he plays chess against the Grim Reaper during the Black Plague.', 'poster.jpg', 96, 22);
INSERT INTO movie VALUES(44, 'Lost in Translation', 2003, 'A faded movie star and a neglected young woman form an unlikely bond after crossing paths in Tokyo.', 'poster.jpg', 102, 38);
INSERT INTO movie VALUES(45, 'Taxi Driver', 1976, 'A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence and sleaze fuels his urge for violent action.', 'poster.jpg', 114, 11);
INSERT INTO movie VALUES(46, 'Spirited Away', 2001, 'During her family''s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.', 'poster.jpg', 125, 39);
INSERT INTO movie VALUES(47, 'Night of the Living Dead', 1968, 'A ragtag group of Pennsylvanians barricade themselves in an old farmhouse to remain safe from a horde of flesh-eating ghouls that are ravaging the East Coast of the United States.', 'poster.jpg', 96, 40);
INSERT INTO movie VALUES(48, 'Battleship Potemkin', 1925, 'In the midst of the Russian Revolution of 1905, the crew of the battleship Potemkin mutiny against the brutal, tyrannical regime of the vessel''s officers. The resulting street demonstration in Odessa brings on a police massacre.', 'poster.jpg', 66, 41);
INSERT INTO movie VALUES(49, 'Modern Times', 1936, 'The Tramp struggles to live in modern industrial society with the help of a young homeless woman.', 'poster.jpg', 87, 16);
INSERT INTO movie VALUES(50, 'Breathless', 1960, 'A small-time thief steals a car and impulsively murders a motorcycle policeman. Wanted by the authorities, he reunites with a hip American journalism student and attempts to persuade her to run away with him to Italy.', 'poster.jpg', 90, 42);
INSERT INTO movie VALUES(51, 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', 1964, 'An insane American general orders a bombing attack on the Soviet Union, triggering a path to nuclear holocaust that a war room full of politicians and generals frantically tries to stop.', 'poster.jpg', 95, 1);
INSERT INTO movie VALUES(52, 'M', 1931, 'When the police in a German city are unable to catch a child-murderer, other criminals join in the manhunt.', 'poster.jpg', 99, 43);
INSERT INTO movie VALUES(53, 'Blade', 1998, 'A half-vampire, half-mortal man becomes a protector of the mortal race, while slaying evil vampires.', 'poster.jpg', 120, 44);
INSERT INTO movie VALUES(54, 'The Bitter Tears of Petra von Kant', 1972, 'A successful fashion designer abandons a sado-masochistic relationship with her female assistant in favor of a love affair with a beautiful young woman.', 'poster.jpg', 124, 45);
INSERT INTO movie VALUES(55, 'Rome, Open City', 1945, 'During the Nazi occupation of Rome in 1944, the Resistance leader, Giorgio Manfredi, is chased by the Nazis as he seeks refuge and a way to escape.', 'poster.jpg', 103, 46);
INSERT INTO movie VALUES(56, 'Nosferatu', 1922, 'Vampire Count Orlok expresses interest in a new residence and real estate agent Hutter''s wife.', 'poster.jpg', 94, 47);
INSERT INTO movie VALUES(57, 'Airplane!', 1980, 'A man afraid to fly must ensure that a plane lands safely after the pilots become sick.', 'poster.jpg', 88, 48);
INSERT INTO movie VALUES(58, 'Under the Skin', 2013, 'A mysterious young woman seduces lonely men in the evening hours in Scotland. However, events lead her to begin a process of self-discovery.', 'poster.jpg', 108, 49);
INSERT INTO movie VALUES(59, 'Mad Max: Fury Road', 2015, 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.', 'poster.jpg', 120, 50);
INSERT INTO movie VALUES(60, 'Apocalypse Now', 1979, 'A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god.', 'poster.jpg', 147, 2);
INSERT INTO movie VALUES(61, 'Brokeback Mountain', 2005, 'Ennis and Jack are two shepherds who develop a sexual and emotional relationship. Their relationship becomes complicated when both of them get married to their respective girlfriends.', 'poster.jpg', 134, 51);
INSERT INTO movie VALUES(62, 'Duck Soup', 1933, 'Rufus T. Firefly is named the dictator of bankrupt Freedonia and declares war on neighboring Sylvania over the love of his wealthy backer Mrs. Teasdale, contending with two inept spies who can''t seem to keep straight which side they''', 'poster.jpg', 69, 52);
INSERT INTO movie VALUES(63, 'The Blair Witch Project', 1999, 'Three film students vanish after traveling into a Maryland forest to film a documentary on the local Blair Witch legend, leaving only their footage behind.', 'poster.jpg', 81, 53);
INSERT INTO movie VALUES(66, 'The General', 1926, 'After being rejected by the Confederate military, not realizing it was due to his crucial civilian role, an engineer must single-handedly recapture his beloved locomotive after it is seized by Union spies and return it through ene...', 'poster.jpg', 67, 54);
INSERT INTO movie VALUES(67, 'Eternal Sunshine of the Spotless Mind', 2004, 'When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.', 'poster.jpg', 108, 55);
INSERT INTO movie VALUES(68, 'The Texas Chain Saw Massacre', 1974, 'Five friends head out to rural Texas to visit the grave of a grandfather. On the way they stumble across what appears to be a deserted house, only to discover something sinister within. Something armed with a chainsaw.', 'poster.jpg', 83, 56);
INSERT INTO movie VALUES(69, 'Come and See', 1985, 'After finding an old rifle, a young boy joins the Soviet resistance movement against ruthless German forces and experiences the horrors of World War II.', 'poster.jpg', 142, 57);
INSERT INTO movie VALUES(70, 'Heat', 1995, 'A group of high-end professional thieves start to feel the heat from the LAPD when they unknowingly leave a clue at their latest heist.', 'poster.jpg', 170, 58);
INSERT INTO movie VALUES(71, 'The Shining', 1980, 'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.', 'poster.jpg', 146, 1);
INSERT INTO movie VALUES(72, 'Toy Story', 1995, 'A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy''s room.', 'poster.jpg', 81, 59);
INSERT INTO movie VALUES(73, 'Killer of Sheep', 1978, 'Set in the Watts area of Los Angeles, a slaughterhouse worker must suspend his emotions to continue working at a job he finds repugnant, and then he finds he has little sensitivity for the family he works so hard to support.', 'poster.jpg', 80, 60);
INSERT INTO movie VALUES(74, 'A Woman Under the Influence', 1974, 'Although wife and mother Mabel is loved by her husband Nick, her mental illness places a strain on the marriage.', 'poster.jpg', 155, 61);
INSERT INTO movie VALUES(75, 'Annie Hall', 1977, 'Alvy Singer, a divorced Jewish comedian, reflects on his relationship with ex-lover Annie Hall, an aspiring nightclub singer, which ended abruptly just like his previous marriages.', 'poster.jpg', 93, 62);
INSERT INTO movie VALUES(76, 'Some Like It Hot', 1959, 'After two male musicians witness a mob hit, they flee the state in an all-female band disguised as women, but further complications set in.', 'poster.jpg', 121, 24);
INSERT INTO movie VALUES(77, 'Metropolis', 1927, 'In a futuristic city sharply divided between the working class and the city planners, the son of the city''s mastermind falls in love with a working-class prophet who predicts the coming of a savior to mediate their differences.', 'poster.jpg', 153, 43);
INSERT INTO movie VALUES(78, 'The Maltese Falcon', 1941, 'San Francisco private detective Sam Spade takes on a case that involves him with three eccentric criminals, a gorgeous liar, and their quest for a priceless statuette, with the stakes rising after his partner is murdered.', 'poster.jpg', 100, 63);
INSERT INTO movie VALUES(79, 'This Is Spinal Tap', 1984, 'Spinal Tap, one of England''s loudest bands, is chronicled by film director Marty DiBergi on what proves to be a fateful tour.', 'poster.jpg', 82, 64);
INSERT INTO movie VALUES(80, 'It Happened One Night', 1934, 'A renegade reporter trailing a young runaway heiress for a big story joins her on a bus heading from Florida to New York, and they end up stuck with each other when the bus leaves them behind at one of the stops.', 'poster.jpg', 105, 65);
INSERT INTO movie VALUES(81, 'Die Hard', 1988, 'An NYPD officer tries to save his wife and several others taken hostage by German terrorists during a Christmas party at the Nakatomi Plaza in Los Angeles.', 'poster.jpg', 132, 66);
INSERT INTO movie VALUES(82, 'The Conformist', 1970, 'A weak-willed Italian man becomes a fascist flunky who goes abroad to arrange the assassination of his old teacher, now a political dissident.', 'poster.jpg', 113, 67);
INSERT INTO movie VALUES(83, 'The Thing', 1982, 'A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.', 'poster.jpg', 109, 68);
INSERT INTO movie VALUES(84, 'Daughters of the Dust', 1991, 'A languid, impressionistic story of three generations of Gullah women living on the South Carolina Sea Islands in 1902.', 'poster.jpg', 113, 69);
INSERT INTO movie VALUES(85, 'Barry Lyndon', 1975, 'An Irish rogue wins the heart of a rich widow and assumes her dead husband''s aristocratic position in 18th-century England.', 'poster.jpg', 185, 1);
INSERT INTO movie VALUES(86, 'Raging Bull', 1980, 'The life of boxer Jake LaMotta, whose violence and temper that led him to the top in the ring destroyed his life outside of it.', 'poster.jpg', 129, 11);
INSERT INTO movie VALUES(87, 'Seven Samurai', 1954, 'A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.', 'poster.jpg', 207, 7);
INSERT INTO movie VALUES(88, 'Aguirre, the Wrath of God', 1972, 'In the 16th century, the ruthless and insane Don Lope de Aguirre leads a Spanish expedition in search of El Dorado.', 'poster.jpg', 95, 70);
INSERT INTO movie VALUES(89, 'The Battle of Algiers', 1966, 'In the 1950s, fear and violence escalate as the people of Algiers fight for independence from the French government.', 'poster.jpg', 121, 71);
INSERT INTO movie VALUES(90, 'Women on the Verge of a Nervous Breakdown', 1988, 'A television actress encounters a variety of eccentric characters after embarking on a journey to discover why her lover abruptly left her.', 'poster.jpg', 88, 72);
INSERT INTO movie VALUES(91, 'Boyhood', 2014, 'The life of Mason, from early childhood to his arrival at college.', 'poster.jpg', 165, 73);
INSERT INTO movie VALUES(92, 'The Discreet Charm of the Bourgeoisie', 1972, 'A surreal, virtually plotless series of dreams centered around six middle-class people and their consistently interrupted attempts to have a meal together.', 'poster.jpg', 102, 74);
INSERT INTO movie VALUES(93, 'Paths of Glory', 1957, 'After refusing to attack an enemy position, a general accuses the soldiers of cowardice and their commanding officer must defend them.', 'poster.jpg', 88, 1);
INSERT INTO movie VALUES(94, 'Fantastic Beasts: The Secrets of Dumbledore', 2022, 'Albus Dumbledore assigns Newt and his allies with a mission related to the rising power of Grindelwald.', 'poster.jpg', 142, 75);
INSERT INTO movie VALUES(95, 'Sweet Smell of Success', 1957, 'Powerful but unethical Broadway columnist J.J. Hunsecker coerces unscrupulous press agent Sidney Falco into breaking up his sister''s romance with a jazz musician.', 'poster.jpg', 96, 76);
INSERT INTO movie VALUES(96, 'The Cabinet of Dr. Caligari', 1920, 'Hypnotist Dr. Caligari uses a somnambulist, Cesare, to commit murders.', 'poster.jpg', 67, 77);
INSERT INTO movie VALUES(97, 'Nashville', 1975, 'Over the course of a few hectic days, numerous interrelated people prepare for a political convention.', 'poster.jpg', 160, 78);
INSERT INTO movie VALUES(99, 'Bonnie and Clyde', 1967, 'Bored waitress Bonnie Parker falls in love with an ex-con named Clyde Barrow and together they start a violent crime spree through the country, stealing cars and robbing banks.', 'poster.jpg', 111, 79);
INSERT INTO movie VALUES(100, 'Get Out', 2017, 'A young African-American visits his white girlfriend''s parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.', 'poster.jpg', 104, 80);

INSERT INTO genremovie VALUES(1, 1);
INSERT INTO genremovie VALUES(2, 1);
INSERT INTO genremovie VALUES(3, 2);
INSERT INTO genremovie VALUES(4, 2);
INSERT INTO genremovie VALUES(4, 3);
INSERT INTO genremovie VALUES(5, 3);
INSERT INTO genremovie VALUES(4, 4);
INSERT INTO genremovie VALUES(1, 5);
INSERT INTO genremovie VALUES(6, 5);
INSERT INTO genremovie VALUES(4, 6);
INSERT INTO genremovie VALUES(7, 6);
INSERT INTO genremovie VALUES(4, 7);
INSERT INTO genremovie VALUES(6, 7);
INSERT INTO genremovie VALUES(4, 8);
INSERT INTO genremovie VALUES(8, 8);
INSERT INTO genremovie VALUES(4, 9);
INSERT INTO genremovie VALUES(7, 10);
INSERT INTO genremovie VALUES(8, 10);
INSERT INTO genremovie VALUES(9, 10);
INSERT INTO genremovie VALUES(3, 11);
INSERT INTO genremovie VALUES(4, 11);
INSERT INTO genremovie VALUES(10, 11);
INSERT INTO genremovie VALUES(1, 12);
INSERT INTO genremovie VALUES(5, 12);
INSERT INTO genremovie VALUES(11, 12);
INSERT INTO genremovie VALUES(4, 13);
INSERT INTO genremovie VALUES(5, 13);
INSERT INTO genremovie VALUES(11, 13);
INSERT INTO genremovie VALUES(4, 14);
INSERT INTO genremovie VALUES(3, 15);
INSERT INTO genremovie VALUES(4, 15);
INSERT INTO genremovie VALUES(6, 15);
INSERT INTO genremovie VALUES(4, 16);
INSERT INTO genremovie VALUES(7, 16);
INSERT INTO genremovie VALUES(8, 16);
INSERT INTO genremovie VALUES(4, 17);
INSERT INTO genremovie VALUES(12, 17);
INSERT INTO genremovie VALUES(4, 18);
INSERT INTO genremovie VALUES(7, 18);
INSERT INTO genremovie VALUES(8, 18);
INSERT INTO genremovie VALUES(4, 19);
INSERT INTO genremovie VALUES(8, 19);
INSERT INTO genremovie VALUES(13, 19);
INSERT INTO genremovie VALUES(5, 20);
INSERT INTO genremovie VALUES(8, 20);
INSERT INTO genremovie VALUES(11, 20);
INSERT INTO genremovie VALUES(4, 21);
INSERT INTO genremovie VALUES(12, 21);
INSERT INTO genremovie VALUES(1, 22);
INSERT INTO genremovie VALUES(4, 22);
INSERT INTO genremovie VALUES(14, 22);
INSERT INTO genremovie VALUES(4, 23);
INSERT INTO genremovie VALUES(11, 23);
INSERT INTO genremovie VALUES(4, 24);
INSERT INTO genremovie VALUES(7, 24);
INSERT INTO genremovie VALUES(3, 25);
INSERT INTO genremovie VALUES(4, 25);
INSERT INTO genremovie VALUES(5, 25);
INSERT INTO genremovie VALUES(4, 26);
INSERT INTO genremovie VALUES(7, 26);
INSERT INTO genremovie VALUES(1, 27);
INSERT INTO genremovie VALUES(11, 27);
INSERT INTO genremovie VALUES(3, 28);
INSERT INTO genremovie VALUES(4, 28);
INSERT INTO genremovie VALUES(15, 28);
INSERT INTO genremovie VALUES(3, 29);
INSERT INTO genremovie VALUES(4, 29);
INSERT INTO genremovie VALUES(1, 30);
INSERT INTO genremovie VALUES(6, 30);
INSERT INTO genremovie VALUES(16, 30);
INSERT INTO genremovie VALUES(4, 31);
INSERT INTO genremovie VALUES(10, 31);
INSERT INTO genremovie VALUES(17, 31);
INSERT INTO genremovie VALUES(14, 32);
INSERT INTO genremovie VALUES(2, 33);
INSERT INTO genremovie VALUES(18, 33);
INSERT INTO genremovie VALUES(4, 34);
INSERT INTO genremovie VALUES(3, 35);
INSERT INTO genremovie VALUES(4, 35);
INSERT INTO genremovie VALUES(4, 36);
INSERT INTO genremovie VALUES(7, 36);
INSERT INTO genremovie VALUES(1, 37);
INSERT INTO genremovie VALUES(4, 37);
INSERT INTO genremovie VALUES(10, 37);
INSERT INTO genremovie VALUES(5, 38);
INSERT INTO genremovie VALUES(11, 38);
INSERT INTO genremovie VALUES(18, 38);
INSERT INTO genremovie VALUES(4, 39);
INSERT INTO genremovie VALUES(4, 40);
INSERT INTO genremovie VALUES(10, 40);
INSERT INTO genremovie VALUES(17, 40);
INSERT INTO genremovie VALUES(4, 41);
INSERT INTO genremovie VALUES(8, 41);
INSERT INTO genremovie VALUES(9, 41);
INSERT INTO genremovie VALUES(4, 42);
INSERT INTO genremovie VALUES(5, 42);
INSERT INTO genremovie VALUES(11, 42);
INSERT INTO genremovie VALUES(4, 43);
INSERT INTO genremovie VALUES(16, 43);
INSERT INTO genremovie VALUES(4, 44);
INSERT INTO genremovie VALUES(7, 44);
INSERT INTO genremovie VALUES(3, 45);
INSERT INTO genremovie VALUES(4, 45);
INSERT INTO genremovie VALUES(1, 46);
INSERT INTO genremovie VALUES(19, 46);
INSERT INTO genremovie VALUES(20, 46);
INSERT INTO genremovie VALUES(11, 47);
INSERT INTO genremovie VALUES(18, 47);
INSERT INTO genremovie VALUES(4, 48);
INSERT INTO genremovie VALUES(11, 48);
INSERT INTO genremovie VALUES(17, 48);
INSERT INTO genremovie VALUES(4, 49);
INSERT INTO genremovie VALUES(7, 49);
INSERT INTO genremovie VALUES(8, 49);
INSERT INTO genremovie VALUES(3, 50);
INSERT INTO genremovie VALUES(4, 50);
INSERT INTO genremovie VALUES(7, 51);
INSERT INTO genremovie VALUES(12, 51);
INSERT INTO genremovie VALUES(3, 52);
INSERT INTO genremovie VALUES(5, 52);
INSERT INTO genremovie VALUES(11, 52);
INSERT INTO genremovie VALUES(2, 53);
INSERT INTO genremovie VALUES(6, 53);
INSERT INTO genremovie VALUES(18, 53);
INSERT INTO genremovie VALUES(4, 54);
INSERT INTO genremovie VALUES(8, 54);
INSERT INTO genremovie VALUES(4, 55);
INSERT INTO genremovie VALUES(11, 55);
INSERT INTO genremovie VALUES(12, 55);
INSERT INTO genremovie VALUES(16, 56);
INSERT INTO genremovie VALUES(18, 56);
INSERT INTO genremovie VALUES(7, 57);
INSERT INTO genremovie VALUES(4, 58);
INSERT INTO genremovie VALUES(5, 58);
INSERT INTO genremovie VALUES(18, 58);
INSERT INTO genremovie VALUES(1, 59);
INSERT INTO genremovie VALUES(2, 59);
INSERT INTO genremovie VALUES(6, 59);
INSERT INTO genremovie VALUES(4, 60);
INSERT INTO genremovie VALUES(5, 60);
INSERT INTO genremovie VALUES(12, 60);
INSERT INTO genremovie VALUES(4, 61);
INSERT INTO genremovie VALUES(8, 61);
INSERT INTO genremovie VALUES(7, 62);
INSERT INTO genremovie VALUES(9, 62);
INSERT INTO genremovie VALUES(5, 63);
INSERT INTO genremovie VALUES(18, 63);
INSERT INTO genremovie VALUES(1, 66);
INSERT INTO genremovie VALUES(6, 66);
INSERT INTO genremovie VALUES(7, 66);
INSERT INTO genremovie VALUES(2, 67);
INSERT INTO genremovie VALUES(4, 67);
INSERT INTO genremovie VALUES(8, 67);
INSERT INTO genremovie VALUES(18, 68);
INSERT INTO genremovie VALUES(4, 69);
INSERT INTO genremovie VALUES(11, 69);
INSERT INTO genremovie VALUES(12, 69);
INSERT INTO genremovie VALUES(3, 70);
INSERT INTO genremovie VALUES(4, 70);
INSERT INTO genremovie VALUES(6, 70);
INSERT INTO genremovie VALUES(4, 71);
INSERT INTO genremovie VALUES(18, 71);
INSERT INTO genremovie VALUES(1, 72);
INSERT INTO genremovie VALUES(7, 72);
INSERT INTO genremovie VALUES(19, 72);
INSERT INTO genremovie VALUES(4, 73);
INSERT INTO genremovie VALUES(4, 74);
INSERT INTO genremovie VALUES(8, 74);
INSERT INTO genremovie VALUES(7, 75);
INSERT INTO genremovie VALUES(8, 75);
INSERT INTO genremovie VALUES(7, 76);
INSERT INTO genremovie VALUES(8, 76);
INSERT INTO genremovie VALUES(13, 76);
INSERT INTO genremovie VALUES(2, 77);
INSERT INTO genremovie VALUES(4, 77);
INSERT INTO genremovie VALUES(3, 78);
INSERT INTO genremovie VALUES(5, 78);
INSERT INTO genremovie VALUES(15, 78);
INSERT INTO genremovie VALUES(7, 79);
INSERT INTO genremovie VALUES(13, 79);
INSERT INTO genremovie VALUES(7, 80);
INSERT INTO genremovie VALUES(8, 80);
INSERT INTO genremovie VALUES(6, 81);
INSERT INTO genremovie VALUES(11, 81);
INSERT INTO genremovie VALUES(4, 82);
INSERT INTO genremovie VALUES(2, 83);
INSERT INTO genremovie VALUES(5, 83);
INSERT INTO genremovie VALUES(18, 83);
INSERT INTO genremovie VALUES(4, 84);
INSERT INTO genremovie VALUES(8, 84);
INSERT INTO genremovie VALUES(17, 84);
INSERT INTO genremovie VALUES(1, 85);
INSERT INTO genremovie VALUES(4, 85);
INSERT INTO genremovie VALUES(12, 85);
INSERT INTO genremovie VALUES(4, 86);
INSERT INTO genremovie VALUES(10, 86);
INSERT INTO genremovie VALUES(21, 86);
INSERT INTO genremovie VALUES(4, 87);
INSERT INTO genremovie VALUES(6, 87);
INSERT INTO genremovie VALUES(1, 88);
INSERT INTO genremovie VALUES(6, 88);
INSERT INTO genremovie VALUES(10, 88);
INSERT INTO genremovie VALUES(4, 89);
INSERT INTO genremovie VALUES(12, 89);
INSERT INTO genremovie VALUES(4, 90);
INSERT INTO genremovie VALUES(7, 90);
INSERT INTO genremovie VALUES(4, 91);
INSERT INTO genremovie VALUES(7, 92);
INSERT INTO genremovie VALUES(4, 93);
INSERT INTO genremovie VALUES(12, 93);
INSERT INTO genremovie VALUES(1, 94);
INSERT INTO genremovie VALUES(16, 94);
INSERT INTO genremovie VALUES(20, 94);
INSERT INTO genremovie VALUES(4, 95);
INSERT INTO genremovie VALUES(15, 95);
INSERT INTO genremovie VALUES(5, 96);
INSERT INTO genremovie VALUES(11, 96);
INSERT INTO genremovie VALUES(18, 96);
INSERT INTO genremovie VALUES(4, 97);
INSERT INTO genremovie VALUES(7, 97);
INSERT INTO genremovie VALUES(13, 97);
INSERT INTO genremovie VALUES(3, 99);
INSERT INTO genremovie VALUES(6, 99);
INSERT INTO genremovie VALUES(10, 99);
INSERT INTO genremovie VALUES(5, 100);
INSERT INTO genremovie VALUES(11, 100);
INSERT INTO genremovie VALUES(18, 100);
INSERT INTO user VALUES(1, 'bob', 'a', 'user');
INSERT INTO user VALUES(2, 'john', 'a', 'user');
INSERT INTO user VALUES(3, 'johnny', 'a', 'user');
INSERT INTO user VALUES(4, 'steve', 'a', 'user');
INSERT INTO user VALUES(5, 'mike', 'a', 'user');
INSERT INTO user VALUES(6, 'kimberley', 'a', 'user');
INSERT INTO user VALUES(7, 'chloe', 'a', 'user');
INSERT INTO user VALUES(8, 'robert', 'a', 'user');
INSERT INTO user VALUES(9, 'ingrid', 'a', 'user');
INSERT INTO rating VALUES(1, 1, 2);
INSERT INTO rating VALUES(1, 2, 5);
INSERT INTO rating VALUES(1, 3, 4);
INSERT INTO rating VALUES(1, 4, 4);
INSERT INTO rating VALUES(1, 5, 2);
INSERT INTO rating VALUES(1, 6, 5);
INSERT INTO rating VALUES(1, 7, 4);
INSERT INTO rating VALUES(1, 8, 1);
INSERT INTO rating VALUES(1, 9, 1);
INSERT INTO rating VALUES(1, 10, 3);
INSERT INTO rating VALUES(1, 11, 3);
INSERT INTO rating VALUES(1, 12, 3);
INSERT INTO rating VALUES(1, 13, 0);
INSERT INTO rating VALUES(1, 14, 5);
INSERT INTO rating VALUES(1, 15, 1);
INSERT INTO rating VALUES(1, 16, 2);
INSERT INTO rating VALUES(1, 17, 2);
INSERT INTO rating VALUES(1, 18, 1);
INSERT INTO rating VALUES(1, 19, 5);
INSERT INTO rating VALUES(1, 20, 5);
INSERT INTO rating VALUES(1, 21, 1);
INSERT INTO rating VALUES(1, 22, 5);
INSERT INTO rating VALUES(1, 23, 0);
INSERT INTO rating VALUES(1, 24, 2);
INSERT INTO rating VALUES(1, 25, 4);
INSERT INTO rating VALUES(1, 26, 1);
INSERT INTO rating VALUES(1, 27, 5);
INSERT INTO rating VALUES(1, 28, 2);
INSERT INTO rating VALUES(1, 29, 0);
INSERT INTO rating VALUES(1, 30, 3);
INSERT INTO rating VALUES(1, 31, 2);
INSERT INTO rating VALUES(1, 32, 3);
INSERT INTO rating VALUES(1, 33, 1);
INSERT INTO rating VALUES(1, 34, 5);
INSERT INTO rating VALUES(1, 35, 2);
INSERT INTO rating VALUES(1, 36, 1);
INSERT INTO rating VALUES(1, 37, 0);
INSERT INTO rating VALUES(1, 38, 4);
INSERT INTO rating VALUES(1, 39, 3);
INSERT INTO rating VALUES(1, 40, 3);
INSERT INTO rating VALUES(1, 41, 1);
INSERT INTO rating VALUES(1, 42, 1);
INSERT INTO rating VALUES(1, 43, 3);
INSERT INTO rating VALUES(1, 44, 3);
INSERT INTO rating VALUES(1, 45, 1);
INSERT INTO rating VALUES(1, 46, 5);
INSERT INTO rating VALUES(1, 47, 2);
INSERT INTO rating VALUES(1, 48, 3);
INSERT INTO rating VALUES(1, 49, 0);
INSERT INTO rating VALUES(1, 50, 0);
INSERT INTO rating VALUES(1, 51, 1);
INSERT INTO rating VALUES(1, 52, 2);
INSERT INTO rating VALUES(1, 53, 4);
INSERT INTO rating VALUES(1, 54, 5);
INSERT INTO rating VALUES(1, 55, 4);
INSERT INTO rating VALUES(1, 56, 1);
INSERT INTO rating VALUES(1, 57, 4);
INSERT INTO rating VALUES(1, 58, 4);
INSERT INTO rating VALUES(1, 59, 5);
INSERT INTO rating VALUES(1, 60, 1);
INSERT INTO rating VALUES(1, 61, 2);
INSERT INTO rating VALUES(1, 62, 2);
INSERT INTO rating VALUES(1, 63, 4);
INSERT INTO rating VALUES(1, 66, 3);
INSERT INTO rating VALUES(1, 67, 2);
INSERT INTO rating VALUES(1, 68, 4);
INSERT INTO rating VALUES(1, 69, 4);
INSERT INTO rating VALUES(1, 70, 3);
INSERT INTO rating VALUES(1, 71, 1);
INSERT INTO rating VALUES(1, 72, 3);
INSERT INTO rating VALUES(1, 73, 4);
INSERT INTO rating VALUES(1, 74, 2);
INSERT INTO rating VALUES(1, 75, 2);
INSERT INTO rating VALUES(1, 76, 5);
INSERT INTO rating VALUES(1, 77, 4);
INSERT INTO rating VALUES(1, 78, 5);
INSERT INTO rating VALUES(1, 79, 2);
INSERT INTO rating VALUES(1, 80, 0);
INSERT INTO rating VALUES(1, 81, 4);
INSERT INTO rating VALUES(1, 82, 2);
INSERT INTO rating VALUES(1, 83, 2);
INSERT INTO rating VALUES(1, 84, 4);
INSERT INTO rating VALUES(1, 85, 4);
INSERT INTO rating VALUES(1, 86, 2);
INSERT INTO rating VALUES(1, 87, 3);
INSERT INTO rating VALUES(1, 88, 0);
INSERT INTO rating VALUES(1, 89, 1);
INSERT INTO rating VALUES(1, 90, 2);
INSERT INTO rating VALUES(1, 91, 5);
INSERT INTO rating VALUES(1, 92, 4);
INSERT INTO rating VALUES(1, 93, 5);
INSERT INTO rating VALUES(1, 94, 0);
INSERT INTO rating VALUES(1, 95, 1);
INSERT INTO rating VALUES(1, 96, 5);
INSERT INTO rating VALUES(1, 97, 3);
INSERT INTO rating VALUES(1, 99, 2);
INSERT INTO rating VALUES(1, 100, 5);
INSERT INTO rating VALUES(2, 1, 5);
INSERT INTO rating VALUES(2, 2, 4);
INSERT INTO rating VALUES(2, 3, 4);
INSERT INTO rating VALUES(2, 4, 0);
INSERT INTO rating VALUES(2, 5, 5);
INSERT INTO rating VALUES(2, 6, 3);
INSERT INTO rating VALUES(2, 7, 4);
INSERT INTO rating VALUES(2, 8, 0);
INSERT INTO rating VALUES(2, 9, 2);
INSERT INTO rating VALUES(2, 10, 4);
INSERT INTO rating VALUES(2, 11, 3);
INSERT INTO rating VALUES(2, 12, 2);
INSERT INTO rating VALUES(2, 13, 4);
INSERT INTO rating VALUES(2, 14, 2);
INSERT INTO rating VALUES(2, 15, 3);
INSERT INTO rating VALUES(2, 16, 4);
INSERT INTO rating VALUES(2, 17, 1);
INSERT INTO rating VALUES(2, 18, 4);
INSERT INTO rating VALUES(2, 19, 5);
INSERT INTO rating VALUES(2, 20, 0);
INSERT INTO rating VALUES(2, 21, 1);
INSERT INTO rating VALUES(2, 22, 5);
INSERT INTO rating VALUES(2, 23, 4);
INSERT INTO rating VALUES(2, 24, 5);
INSERT INTO rating VALUES(2, 25, 4);
INSERT INTO rating VALUES(2, 26, 1);
INSERT INTO rating VALUES(2, 27, 4);
INSERT INTO rating VALUES(2, 28, 3);
INSERT INTO rating VALUES(2, 29, 4);
INSERT INTO rating VALUES(2, 30, 3);
INSERT INTO rating VALUES(2, 31, 5);
INSERT INTO rating VALUES(2, 32, 1);
INSERT INTO rating VALUES(2, 33, 0);
INSERT INTO rating VALUES(2, 34, 0);
INSERT INTO rating VALUES(2, 35, 2);
INSERT INTO rating VALUES(2, 36, 0);
INSERT INTO rating VALUES(2, 37, 1);
INSERT INTO rating VALUES(2, 38, 1);
INSERT INTO rating VALUES(2, 39, 3);
INSERT INTO rating VALUES(2, 40, 4);
INSERT INTO rating VALUES(2, 41, 3);
INSERT INTO rating VALUES(2, 42, 2);
INSERT INTO rating VALUES(2, 43, 3);
INSERT INTO rating VALUES(2, 44, 3);
INSERT INTO rating VALUES(2, 45, 5);
INSERT INTO rating VALUES(2, 46, 4);
INSERT INTO rating VALUES(2, 47, 3);
INSERT INTO rating VALUES(2, 48, 5);
INSERT INTO rating VALUES(2, 49, 2);
INSERT INTO rating VALUES(2, 50, 4);
INSERT INTO rating VALUES(2, 51, 0);
INSERT INTO rating VALUES(2, 52, 0);
INSERT INTO rating VALUES(2, 53, 2);
INSERT INTO rating VALUES(2, 54, 1);
INSERT INTO rating VALUES(2, 55, 5);
INSERT INTO rating VALUES(2, 56, 5);
INSERT INTO rating VALUES(2, 57, 2);
INSERT INTO rating VALUES(2, 58, 5);
INSERT INTO rating VALUES(2, 59, 5);
INSERT INTO rating VALUES(2, 60, 1);
INSERT INTO rating VALUES(2, 61, 3);
INSERT INTO rating VALUES(2, 62, 4);
INSERT INTO rating VALUES(2, 63, 5);
INSERT INTO rating VALUES(2, 66, 4);
INSERT INTO rating VALUES(2, 67, 2);
INSERT INTO rating VALUES(2, 68, 5);
INSERT INTO rating VALUES(2, 69, 2);
INSERT INTO rating VALUES(2, 70, 5);
INSERT INTO rating VALUES(2, 71, 1);
INSERT INTO rating VALUES(2, 72, 0);
INSERT INTO rating VALUES(2, 73, 4);
INSERT INTO rating VALUES(2, 74, 5);
INSERT INTO rating VALUES(2, 75, 3);
INSERT INTO rating VALUES(2, 76, 1);
INSERT INTO rating VALUES(2, 77, 2);
INSERT INTO rating VALUES(2, 78, 4);
INSERT INTO rating VALUES(2, 79, 3);
INSERT INTO rating VALUES(2, 80, 0);
INSERT INTO rating VALUES(2, 81, 5);
INSERT INTO rating VALUES(2, 82, 5);
INSERT INTO rating VALUES(2, 83, 3);
INSERT INTO rating VALUES(2, 84, 3);
INSERT INTO rating VALUES(2, 85, 1);
INSERT INTO rating VALUES(2, 86, 3);
INSERT INTO rating VALUES(2, 87, 4);
INSERT INTO rating VALUES(2, 88, 3);
INSERT INTO rating VALUES(2, 89, 1);
INSERT INTO rating VALUES(2, 90, 4);
INSERT INTO rating VALUES(2, 91, 1);
INSERT INTO rating VALUES(2, 92, 3);
INSERT INTO rating VALUES(2, 93, 1);
INSERT INTO rating VALUES(2, 94, 0);
INSERT INTO rating VALUES(2, 95, 0);
INSERT INTO rating VALUES(2, 96, 4);
INSERT INTO rating VALUES(2, 97, 3);
INSERT INTO rating VALUES(2, 99, 3);
INSERT INTO rating VALUES(2, 100, 2);
INSERT INTO rating VALUES(3, 1, 5);
INSERT INTO rating VALUES(3, 2, 0);
INSERT INTO rating VALUES(3, 3, 0);
INSERT INTO rating VALUES(3, 4, 5);
INSERT INTO rating VALUES(3, 5, 3);
INSERT INTO rating VALUES(3, 6, 1);
INSERT INTO rating VALUES(3, 7, 0);
INSERT INTO rating VALUES(3, 8, 5);
INSERT INTO rating VALUES(3, 9, 2);
INSERT INTO rating VALUES(3, 10, 1);
INSERT INTO rating VALUES(3, 11, 3);
INSERT INTO rating VALUES(3, 12, 0);
INSERT INTO rating VALUES(3, 13, 4);
INSERT INTO rating VALUES(3, 14, 1);
INSERT INTO rating VALUES(3, 15, 5);
INSERT INTO rating VALUES(3, 16, 4);
INSERT INTO rating VALUES(3, 17, 2);
INSERT INTO rating VALUES(3, 18, 5);
INSERT INTO rating VALUES(3, 19, 2);
INSERT INTO rating VALUES(3, 20, 4);
INSERT INTO rating VALUES(3, 21, 1);
INSERT INTO rating VALUES(3, 22, 3);
INSERT INTO rating VALUES(3, 23, 1);
INSERT INTO rating VALUES(3, 24, 4);
INSERT INTO rating VALUES(3, 25, 5);
INSERT INTO rating VALUES(3, 26, 2);
INSERT INTO rating VALUES(3, 27, 4);
INSERT INTO rating VALUES(3, 28, 5);
INSERT INTO rating VALUES(3, 29, 5);
INSERT INTO rating VALUES(3, 30, 4);
INSERT INTO rating VALUES(3, 31, 0);
INSERT INTO rating VALUES(3, 32, 4);
INSERT INTO rating VALUES(3, 33, 2);
INSERT INTO rating VALUES(3, 34, 0);
INSERT INTO rating VALUES(3, 35, 2);
INSERT INTO rating VALUES(3, 36, 5);
INSERT INTO rating VALUES(3, 37, 3);
INSERT INTO rating VALUES(3, 38, 1);
INSERT INTO rating VALUES(3, 39, 0);
INSERT INTO rating VALUES(3, 40, 1);
INSERT INTO rating VALUES(3, 41, 4);
INSERT INTO rating VALUES(3, 42, 3);
INSERT INTO rating VALUES(3, 43, 2);
INSERT INTO rating VALUES(3, 44, 3);
INSERT INTO rating VALUES(3, 45, 4);
INSERT INTO rating VALUES(3, 46, 0);
INSERT INTO rating VALUES(3, 47, 5);
INSERT INTO rating VALUES(3, 48, 0);
INSERT INTO rating VALUES(3, 49, 5);
INSERT INTO rating VALUES(3, 50, 2);
INSERT INTO rating VALUES(3, 51, 3);
INSERT INTO rating VALUES(3, 52, 3);
INSERT INTO rating VALUES(3, 53, 5);
INSERT INTO rating VALUES(3, 54, 1);
INSERT INTO rating VALUES(3, 55, 3);
INSERT INTO rating VALUES(3, 56, 5);
INSERT INTO rating VALUES(3, 57, 3);
INSERT INTO rating VALUES(3, 58, 2);
INSERT INTO rating VALUES(3, 59, 0);
INSERT INTO rating VALUES(3, 60, 1);
INSERT INTO rating VALUES(3, 61, 3);
INSERT INTO rating VALUES(3, 62, 4);
INSERT INTO rating VALUES(3, 63, 0);
INSERT INTO rating VALUES(3, 66, 5);
INSERT INTO rating VALUES(3, 67, 0);
INSERT INTO rating VALUES(3, 68, 4);
INSERT INTO rating VALUES(3, 69, 4);
INSERT INTO rating VALUES(3, 70, 4);
INSERT INTO rating VALUES(3, 71, 3);
INSERT INTO rating VALUES(3, 72, 4);
INSERT INTO rating VALUES(3, 73, 3);
INSERT INTO rating VALUES(3, 74, 0);
INSERT INTO rating VALUES(3, 75, 4);
INSERT INTO rating VALUES(3, 76, 3);
INSERT INTO rating VALUES(3, 77, 4);
INSERT INTO rating VALUES(3, 78, 0);
INSERT INTO rating VALUES(3, 79, 2);
INSERT INTO rating VALUES(3, 80, 0);
INSERT INTO rating VALUES(3, 81, 3);
INSERT INTO rating VALUES(3, 82, 0);
INSERT INTO rating VALUES(3, 83, 3);
INSERT INTO rating VALUES(3, 84, 2);
INSERT INTO rating VALUES(3, 85, 5);
INSERT INTO rating VALUES(3, 86, 2);
INSERT INTO rating VALUES(3, 87, 4);
INSERT INTO rating VALUES(3, 88, 1);
INSERT INTO rating VALUES(3, 89, 4);
INSERT INTO rating VALUES(3, 90, 5);
INSERT INTO rating VALUES(3, 91, 2);
INSERT INTO rating VALUES(3, 92, 3);
INSERT INTO rating VALUES(3, 93, 4);
INSERT INTO rating VALUES(3, 94, 1);
INSERT INTO rating VALUES(3, 95, 5);
INSERT INTO rating VALUES(3, 96, 2);
INSERT INTO rating VALUES(3, 97, 3);
INSERT INTO rating VALUES(3, 99, 4);
INSERT INTO rating VALUES(3, 100, 0);
INSERT INTO rating VALUES(4, 1, 4);
INSERT INTO rating VALUES(4, 2, 5);
INSERT INTO rating VALUES(4, 3, 0);
INSERT INTO rating VALUES(4, 4, 3);
INSERT INTO rating VALUES(4, 5, 2);
INSERT INTO rating VALUES(4, 6, 5);
INSERT INTO rating VALUES(4, 7, 0);
INSERT INTO rating VALUES(4, 8, 0);
INSERT INTO rating VALUES(4, 9, 0);
INSERT INTO rating VALUES(4, 10, 3);
INSERT INTO rating VALUES(4, 11, 0);
INSERT INTO rating VALUES(4, 12, 0);
INSERT INTO rating VALUES(4, 13, 5);
INSERT INTO rating VALUES(4, 14, 2);
INSERT INTO rating VALUES(4, 15, 5);
INSERT INTO rating VALUES(4, 16, 2);
INSERT INTO rating VALUES(4, 17, 3);
INSERT INTO rating VALUES(4, 18, 5);
INSERT INTO rating VALUES(4, 19, 3);
INSERT INTO rating VALUES(4, 20, 1);
INSERT INTO rating VALUES(4, 21, 4);
INSERT INTO rating VALUES(4, 22, 3);
INSERT INTO rating VALUES(4, 23, 5);
INSERT INTO rating VALUES(4, 24, 1);
INSERT INTO rating VALUES(4, 25, 1);
INSERT INTO rating VALUES(4, 26, 3);
INSERT INTO rating VALUES(4, 27, 5);
INSERT INTO rating VALUES(4, 28, 5);
INSERT INTO rating VALUES(4, 29, 5);
INSERT INTO rating VALUES(4, 30, 4);
INSERT INTO rating VALUES(4, 31, 0);
INSERT INTO rating VALUES(4, 32, 5);
INSERT INTO rating VALUES(4, 33, 1);
INSERT INTO rating VALUES(4, 34, 0);
INSERT INTO rating VALUES(4, 35, 5);
INSERT INTO rating VALUES(4, 36, 0);
INSERT INTO rating VALUES(4, 37, 0);
INSERT INTO rating VALUES(4, 38, 5);
INSERT INTO rating VALUES(4, 39, 2);
INSERT INTO rating VALUES(4, 40, 2);
INSERT INTO rating VALUES(4, 41, 4);
INSERT INTO rating VALUES(4, 42, 5);
INSERT INTO rating VALUES(4, 43, 2);
INSERT INTO rating VALUES(4, 44, 1);
INSERT INTO rating VALUES(4, 45, 0);
INSERT INTO rating VALUES(4, 46, 4);
INSERT INTO rating VALUES(4, 47, 1);
INSERT INTO rating VALUES(4, 48, 0);
INSERT INTO rating VALUES(4, 49, 2);
INSERT INTO rating VALUES(4, 50, 3);
INSERT INTO rating VALUES(4, 51, 3);
INSERT INTO rating VALUES(4, 52, 2);
INSERT INTO rating VALUES(4, 53, 3);
INSERT INTO rating VALUES(4, 54, 5);
INSERT INTO rating VALUES(4, 55, 2);
INSERT INTO rating VALUES(4, 56, 2);
INSERT INTO rating VALUES(4, 57, 5);
INSERT INTO rating VALUES(4, 58, 1);
INSERT INTO rating VALUES(4, 59, 0);
INSERT INTO rating VALUES(4, 60, 5);
INSERT INTO rating VALUES(4, 61, 0);
INSERT INTO rating VALUES(4, 62, 4);
INSERT INTO rating VALUES(4, 63, 2);
INSERT INTO rating VALUES(4, 66, 4);
INSERT INTO rating VALUES(4, 67, 2);
INSERT INTO rating VALUES(4, 68, 4);
INSERT INTO rating VALUES(4, 69, 5);
INSERT INTO rating VALUES(4, 70, 3);
INSERT INTO rating VALUES(4, 71, 0);
INSERT INTO rating VALUES(4, 72, 0);
INSERT INTO rating VALUES(4, 73, 0);
INSERT INTO rating VALUES(4, 74, 3);
INSERT INTO rating VALUES(4, 75, 2);
INSERT INTO rating VALUES(4, 76, 0);
INSERT INTO rating VALUES(4, 77, 2);
INSERT INTO rating VALUES(4, 78, 5);
INSERT INTO rating VALUES(4, 79, 1);
INSERT INTO rating VALUES(4, 80, 2);
INSERT INTO rating VALUES(4, 81, 0);
INSERT INTO rating VALUES(4, 82, 0);
INSERT INTO rating VALUES(4, 83, 5);
INSERT INTO rating VALUES(4, 84, 2);
INSERT INTO rating VALUES(4, 85, 1);
INSERT INTO rating VALUES(4, 86, 3);
INSERT INTO rating VALUES(4, 87, 3);
INSERT INTO rating VALUES(4, 88, 2);
INSERT INTO rating VALUES(4, 89, 1);
INSERT INTO rating VALUES(4, 90, 1);
INSERT INTO rating VALUES(4, 91, 3);
INSERT INTO rating VALUES(4, 92, 1);
INSERT INTO rating VALUES(4, 93, 4);
INSERT INTO rating VALUES(4, 94, 2);
INSERT INTO rating VALUES(4, 95, 1);
INSERT INTO rating VALUES(4, 96, 0);
INSERT INTO rating VALUES(4, 97, 5);
INSERT INTO rating VALUES(4, 99, 3);
INSERT INTO rating VALUES(4, 100, 4);
INSERT INTO rating VALUES(5, 1, 2);
INSERT INTO rating VALUES(5, 2, 1);
INSERT INTO rating VALUES(5, 3, 4);
INSERT INTO rating VALUES(5, 4, 0);
INSERT INTO rating VALUES(5, 5, 5);
INSERT INTO rating VALUES(5, 6, 2);
INSERT INTO rating VALUES(5, 7, 3);
INSERT INTO rating VALUES(5, 8, 5);
INSERT INTO rating VALUES(5, 9, 3);
INSERT INTO rating VALUES(5, 10, 1);
INSERT INTO rating VALUES(5, 11, 0);
INSERT INTO rating VALUES(5, 12, 4);
INSERT INTO rating VALUES(5, 13, 5);
INSERT INTO rating VALUES(5, 14, 1);
INSERT INTO rating VALUES(5, 15, 0);
INSERT INTO rating VALUES(5, 16, 5);
INSERT INTO rating VALUES(5, 17, 0);
INSERT INTO rating VALUES(5, 18, 0);
INSERT INTO rating VALUES(5, 19, 1);
INSERT INTO rating VALUES(5, 20, 3);
INSERT INTO rating VALUES(5, 21, 0);
INSERT INTO rating VALUES(5, 22, 4);
INSERT INTO rating VALUES(5, 23, 0);
INSERT INTO rating VALUES(5, 24, 0);
INSERT INTO rating VALUES(5, 25, 5);
INSERT INTO rating VALUES(5, 26, 1);
INSERT INTO rating VALUES(5, 27, 3);
INSERT INTO rating VALUES(5, 28, 1);
INSERT INTO rating VALUES(5, 29, 5);
INSERT INTO rating VALUES(5, 30, 4);
INSERT INTO rating VALUES(5, 31, 0);
INSERT INTO rating VALUES(5, 32, 3);
INSERT INTO rating VALUES(5, 33, 0);
INSERT INTO rating VALUES(5, 34, 0);
INSERT INTO rating VALUES(5, 35, 2);
INSERT INTO rating VALUES(5, 36, 3);
INSERT INTO rating VALUES(5, 37, 4);
INSERT INTO rating VALUES(5, 38, 1);
INSERT INTO rating VALUES(5, 39, 1);
INSERT INTO rating VALUES(5, 40, 0);
INSERT INTO rating VALUES(5, 41, 0);
INSERT INTO rating VALUES(5, 42, 0);
INSERT INTO rating VALUES(5, 43, 3);
INSERT INTO rating VALUES(5, 44, 1);
INSERT INTO rating VALUES(5, 45, 1);
INSERT INTO rating VALUES(5, 46, 5);
INSERT INTO rating VALUES(5, 47, 5);
INSERT INTO rating VALUES(5, 48, 0);
INSERT INTO rating VALUES(5, 49, 3);
INSERT INTO rating VALUES(5, 50, 5);
INSERT INTO rating VALUES(5, 51, 2);
INSERT INTO rating VALUES(5, 52, 5);
INSERT INTO rating VALUES(5, 53, 4);
INSERT INTO rating VALUES(5, 54, 3);
INSERT INTO rating VALUES(5, 55, 5);
INSERT INTO rating VALUES(5, 56, 0);
INSERT INTO rating VALUES(5, 57, 3);
INSERT INTO rating VALUES(5, 58, 4);
INSERT INTO rating VALUES(5, 59, 3);
INSERT INTO rating VALUES(5, 60, 0);
INSERT INTO rating VALUES(5, 61, 0);
INSERT INTO rating VALUES(5, 62, 4);
INSERT INTO rating VALUES(5, 63, 0);
INSERT INTO rating VALUES(5, 66, 3);
INSERT INTO rating VALUES(5, 67, 4);
INSERT INTO rating VALUES(5, 68, 1);
INSERT INTO rating VALUES(5, 69, 3);
INSERT INTO rating VALUES(5, 70, 5);
INSERT INTO rating VALUES(5, 71, 2);
INSERT INTO rating VALUES(5, 72, 5);
INSERT INTO rating VALUES(5, 73, 5);
INSERT INTO rating VALUES(5, 74, 4);
INSERT INTO rating VALUES(5, 75, 3);
INSERT INTO rating VALUES(5, 76, 3);
INSERT INTO rating VALUES(5, 77, 5);
INSERT INTO rating VALUES(5, 78, 3);
INSERT INTO rating VALUES(5, 79, 2);
INSERT INTO rating VALUES(5, 80, 2);
INSERT INTO rating VALUES(5, 81, 5);
INSERT INTO rating VALUES(5, 82, 3);
INSERT INTO rating VALUES(5, 83, 1);
INSERT INTO rating VALUES(5, 84, 5);
INSERT INTO rating VALUES(5, 85, 3);
INSERT INTO rating VALUES(5, 86, 3);
INSERT INTO rating VALUES(5, 87, 1);
INSERT INTO rating VALUES(5, 88, 4);
INSERT INTO rating VALUES(5, 89, 1);
INSERT INTO rating VALUES(5, 90, 3);
INSERT INTO rating VALUES(5, 91, 1);
INSERT INTO rating VALUES(5, 92, 0);
INSERT INTO rating VALUES(5, 93, 4);
INSERT INTO rating VALUES(5, 94, 5);
INSERT INTO rating VALUES(5, 95, 2);
INSERT INTO rating VALUES(5, 96, 3);
INSERT INTO rating VALUES(5, 97, 2);
INSERT INTO rating VALUES(5, 99, 0);
INSERT INTO rating VALUES(5, 100, 0);
INSERT INTO rating VALUES(6, 1, 1);
INSERT INTO rating VALUES(6, 2, 1);
INSERT INTO rating VALUES(6, 3, 2);
INSERT INTO rating VALUES(6, 4, 4);
INSERT INTO rating VALUES(6, 5, 2);
INSERT INTO rating VALUES(6, 6, 3);
INSERT INTO rating VALUES(6, 7, 1);
INSERT INTO rating VALUES(6, 8, 0);
INSERT INTO rating VALUES(6, 9, 1);
INSERT INTO rating VALUES(6, 10, 3);
INSERT INTO rating VALUES(6, 11, 0);
INSERT INTO rating VALUES(6, 12, 3);
INSERT INTO rating VALUES(6, 13, 0);
INSERT INTO rating VALUES(6, 14, 5);
INSERT INTO rating VALUES(6, 15, 2);
INSERT INTO rating VALUES(6, 16, 4);
INSERT INTO rating VALUES(6, 17, 5);
INSERT INTO rating VALUES(6, 18, 1);
INSERT INTO rating VALUES(6, 19, 4);
INSERT INTO rating VALUES(6, 20, 1);
INSERT INTO rating VALUES(6, 21, 0);
INSERT INTO rating VALUES(6, 22, 0);
INSERT INTO rating VALUES(6, 23, 5);
INSERT INTO rating VALUES(6, 24, 1);
INSERT INTO rating VALUES(6, 25, 5);
INSERT INTO rating VALUES(6, 26, 0);
INSERT INTO rating VALUES(6, 27, 3);
INSERT INTO rating VALUES(6, 28, 5);
INSERT INTO rating VALUES(6, 29, 0);
INSERT INTO rating VALUES(6, 30, 1);
INSERT INTO rating VALUES(6, 31, 3);
INSERT INTO rating VALUES(6, 32, 5);
INSERT INTO rating VALUES(6, 33, 0);
INSERT INTO rating VALUES(6, 34, 5);
INSERT INTO rating VALUES(6, 35, 3);
INSERT INTO rating VALUES(6, 36, 1);
INSERT INTO rating VALUES(6, 37, 1);
INSERT INTO rating VALUES(6, 38, 5);
INSERT INTO rating VALUES(6, 39, 2);
INSERT INTO rating VALUES(6, 40, 5);
INSERT INTO rating VALUES(6, 41, 0);
INSERT INTO rating VALUES(6, 42, 2);
INSERT INTO rating VALUES(6, 43, 0);
INSERT INTO rating VALUES(6, 44, 1);
INSERT INTO rating VALUES(6, 45, 0);
INSERT INTO rating VALUES(6, 46, 1);
INSERT INTO rating VALUES(6, 47, 0);
INSERT INTO rating VALUES(6, 48, 4);
INSERT INTO rating VALUES(6, 49, 1);
INSERT INTO rating VALUES(6, 50, 3);
INSERT INTO rating VALUES(6, 51, 2);
INSERT INTO rating VALUES(6, 52, 0);
INSERT INTO rating VALUES(6, 53, 2);
INSERT INTO rating VALUES(6, 54, 0);
INSERT INTO rating VALUES(6, 55, 4);
INSERT INTO rating VALUES(6, 56, 4);
INSERT INTO rating VALUES(6, 57, 2);
INSERT INTO rating VALUES(6, 58, 0);
INSERT INTO rating VALUES(6, 59, 5);
INSERT INTO rating VALUES(6, 60, 0);
INSERT INTO rating VALUES(6, 61, 5);
INSERT INTO rating VALUES(6, 62, 3);
INSERT INTO rating VALUES(6, 63, 1);
INSERT INTO rating VALUES(6, 66, 3);
INSERT INTO rating VALUES(6, 67, 3);
INSERT INTO rating VALUES(6, 68, 2);
INSERT INTO rating VALUES(6, 69, 1);
INSERT INTO rating VALUES(6, 70, 1);
INSERT INTO rating VALUES(6, 71, 0);
INSERT INTO rating VALUES(6, 72, 3);
INSERT INTO rating VALUES(6, 73, 2);
INSERT INTO rating VALUES(6, 74, 2);
INSERT INTO rating VALUES(6, 75, 4);
INSERT INTO rating VALUES(6, 76, 5);
INSERT INTO rating VALUES(6, 77, 2);
INSERT INTO rating VALUES(6, 78, 1);
INSERT INTO rating VALUES(6, 79, 0);
INSERT INTO rating VALUES(6, 80, 2);
INSERT INTO rating VALUES(6, 81, 5);
INSERT INTO rating VALUES(6, 82, 0);
INSERT INTO rating VALUES(6, 83, 5);
INSERT INTO rating VALUES(6, 84, 4);
INSERT INTO rating VALUES(6, 85, 3);
INSERT INTO rating VALUES(6, 86, 0);
INSERT INTO rating VALUES(6, 87, 2);
INSERT INTO rating VALUES(6, 88, 4);
INSERT INTO rating VALUES(6, 89, 1);
INSERT INTO rating VALUES(6, 90, 3);
INSERT INTO rating VALUES(6, 91, 4);
INSERT INTO rating VALUES(6, 92, 5);
INSERT INTO rating VALUES(6, 93, 2);
INSERT INTO rating VALUES(6, 94, 5);
INSERT INTO rating VALUES(6, 95, 2);
INSERT INTO rating VALUES(6, 96, 0);
INSERT INTO rating VALUES(6, 97, 2);
INSERT INTO rating VALUES(6, 99, 3);
INSERT INTO rating VALUES(6, 100, 2);
INSERT INTO rating VALUES(7, 1, 4);
INSERT INTO rating VALUES(7, 2, 4);
INSERT INTO rating VALUES(7, 3, 2);
INSERT INTO rating VALUES(7, 4, 5);
INSERT INTO rating VALUES(7, 5, 3);
INSERT INTO rating VALUES(7, 6, 4);
INSERT INTO rating VALUES(7, 7, 4);
INSERT INTO rating VALUES(7, 8, 3);
INSERT INTO rating VALUES(7, 9, 1);
INSERT INTO rating VALUES(7, 10, 2);
INSERT INTO rating VALUES(7, 11, 1);
INSERT INTO rating VALUES(7, 12, 0);
INSERT INTO rating VALUES(7, 13, 3);
INSERT INTO rating VALUES(7, 14, 3);
INSERT INTO rating VALUES(7, 15, 3);
INSERT INTO rating VALUES(7, 16, 0);
INSERT INTO rating VALUES(7, 17, 4);
INSERT INTO rating VALUES(7, 18, 2);
INSERT INTO rating VALUES(7, 19, 0);
INSERT INTO rating VALUES(7, 20, 5);
INSERT INTO rating VALUES(7, 21, 3);
INSERT INTO rating VALUES(7, 22, 4);
INSERT INTO rating VALUES(7, 23, 1);
INSERT INTO rating VALUES(7, 24, 3);
INSERT INTO rating VALUES(7, 25, 0);
INSERT INTO rating VALUES(7, 26, 3);
INSERT INTO rating VALUES(7, 27, 3);
INSERT INTO rating VALUES(7, 28, 4);
INSERT INTO rating VALUES(7, 29, 5);
INSERT INTO rating VALUES(7, 30, 4);
INSERT INTO rating VALUES(7, 31, 4);
INSERT INTO rating VALUES(7, 32, 1);
INSERT INTO rating VALUES(7, 33, 1);
INSERT INTO rating VALUES(7, 34, 1);
INSERT INTO rating VALUES(7, 35, 4);
INSERT INTO rating VALUES(7, 36, 3);
INSERT INTO rating VALUES(7, 37, 3);
INSERT INTO rating VALUES(7, 38, 4);
INSERT INTO rating VALUES(7, 39, 3);
INSERT INTO rating VALUES(7, 40, 1);
INSERT INTO rating VALUES(7, 41, 1);
INSERT INTO rating VALUES(7, 42, 0);
INSERT INTO rating VALUES(7, 43, 5);
INSERT INTO rating VALUES(7, 44, 0);
INSERT INTO rating VALUES(7, 45, 3);
INSERT INTO rating VALUES(7, 46, 0);
INSERT INTO rating VALUES(7, 47, 4);
INSERT INTO rating VALUES(7, 48, 2);
INSERT INTO rating VALUES(7, 49, 3);
INSERT INTO rating VALUES(7, 50, 0);
INSERT INTO rating VALUES(7, 51, 4);
INSERT INTO rating VALUES(7, 52, 1);
INSERT INTO rating VALUES(7, 53, 5);
INSERT INTO rating VALUES(7, 54, 1);
INSERT INTO rating VALUES(7, 55, 2);
INSERT INTO rating VALUES(7, 56, 5);
INSERT INTO rating VALUES(7, 57, 2);
INSERT INTO rating VALUES(7, 58, 4);
INSERT INTO rating VALUES(7, 59, 1);
INSERT INTO rating VALUES(7, 60, 0);
INSERT INTO rating VALUES(7, 61, 0);
INSERT INTO rating VALUES(7, 62, 0);
INSERT INTO rating VALUES(7, 63, 0);
INSERT INTO rating VALUES(7, 66, 5);
INSERT INTO rating VALUES(7, 67, 1);
INSERT INTO rating VALUES(7, 68, 5);
INSERT INTO rating VALUES(7, 69, 2);
INSERT INTO rating VALUES(7, 70, 0);
INSERT INTO rating VALUES(7, 71, 1);
INSERT INTO rating VALUES(7, 72, 4);
INSERT INTO rating VALUES(7, 73, 5);
INSERT INTO rating VALUES(7, 74, 3);
INSERT INTO rating VALUES(7, 75, 3);
INSERT INTO rating VALUES(7, 76, 2);
INSERT INTO rating VALUES(7, 77, 3);
INSERT INTO rating VALUES(7, 78, 5);
INSERT INTO rating VALUES(7, 79, 5);
INSERT INTO rating VALUES(7, 80, 3);
INSERT INTO rating VALUES(7, 81, 1);
INSERT INTO rating VALUES(7, 82, 0);
INSERT INTO rating VALUES(7, 83, 2);
INSERT INTO rating VALUES(7, 84, 4);
INSERT INTO rating VALUES(7, 85, 4);
INSERT INTO rating VALUES(7, 86, 0);
INSERT INTO rating VALUES(7, 87, 0);
INSERT INTO rating VALUES(7, 88, 0);
INSERT INTO rating VALUES(7, 89, 3);
INSERT INTO rating VALUES(7, 90, 2);
INSERT INTO rating VALUES(7, 91, 2);
INSERT INTO rating VALUES(7, 92, 4);
INSERT INTO rating VALUES(7, 93, 4);
INSERT INTO rating VALUES(7, 94, 3);
INSERT INTO rating VALUES(7, 95, 5);
INSERT INTO rating VALUES(7, 96, 4);
INSERT INTO rating VALUES(7, 97, 2);
INSERT INTO rating VALUES(7, 99, 0);
INSERT INTO rating VALUES(7, 100, 1);
INSERT INTO rating VALUES(8, 1, 2);
INSERT INTO rating VALUES(8, 2, 2);
INSERT INTO rating VALUES(8, 3, 2);
INSERT INTO rating VALUES(8, 4, 2);
INSERT INTO rating VALUES(8, 5, 4);
INSERT INTO rating VALUES(8, 6, 4);
INSERT INTO rating VALUES(8, 7, 3);
INSERT INTO rating VALUES(8, 8, 2);
INSERT INTO rating VALUES(8, 9, 1);
INSERT INTO rating VALUES(8, 10, 3);
INSERT INTO rating VALUES(8, 11, 1);
INSERT INTO rating VALUES(8, 12, 1);
INSERT INTO rating VALUES(8, 13, 4);
INSERT INTO rating VALUES(8, 14, 3);
INSERT INTO rating VALUES(8, 15, 1);
INSERT INTO rating VALUES(8, 16, 4);
INSERT INTO rating VALUES(8, 17, 5);
INSERT INTO rating VALUES(8, 18, 1);
INSERT INTO rating VALUES(8, 19, 1);
INSERT INTO rating VALUES(8, 20, 0);
INSERT INTO rating VALUES(8, 21, 0);
INSERT INTO rating VALUES(8, 22, 1);
INSERT INTO rating VALUES(8, 23, 2);
INSERT INTO rating VALUES(8, 24, 5);
INSERT INTO rating VALUES(8, 25, 5);
INSERT INTO rating VALUES(8, 26, 5);
INSERT INTO rating VALUES(8, 27, 4);
INSERT INTO rating VALUES(8, 28, 4);
INSERT INTO rating VALUES(8, 29, 4);
INSERT INTO rating VALUES(8, 30, 4);
INSERT INTO rating VALUES(8, 31, 3);
INSERT INTO rating VALUES(8, 32, 3);
INSERT INTO rating VALUES(8, 33, 4);
INSERT INTO rating VALUES(8, 34, 3);
INSERT INTO rating VALUES(8, 35, 4);
INSERT INTO rating VALUES(8, 36, 1);
INSERT INTO rating VALUES(8, 37, 2);
INSERT INTO rating VALUES(8, 38, 0);
INSERT INTO rating VALUES(8, 39, 4);
INSERT INTO rating VALUES(8, 40, 5);
INSERT INTO rating VALUES(8, 41, 0);
INSERT INTO rating VALUES(8, 42, 3);
INSERT INTO rating VALUES(8, 43, 4);
INSERT INTO rating VALUES(8, 44, 5);
INSERT INTO rating VALUES(8, 45, 0);
INSERT INTO rating VALUES(8, 46, 3);
INSERT INTO rating VALUES(8, 47, 4);
INSERT INTO rating VALUES(8, 48, 2);
INSERT INTO rating VALUES(8, 49, 2);
INSERT INTO rating VALUES(8, 50, 3);
INSERT INTO rating VALUES(8, 51, 5);
INSERT INTO rating VALUES(8, 52, 5);
INSERT INTO rating VALUES(8, 53, 1);
INSERT INTO rating VALUES(8, 54, 4);
INSERT INTO rating VALUES(8, 55, 4);
INSERT INTO rating VALUES(8, 56, 3);
INSERT INTO rating VALUES(8, 57, 1);
INSERT INTO rating VALUES(8, 58, 3);
INSERT INTO rating VALUES(8, 59, 0);
INSERT INTO rating VALUES(8, 60, 2);
INSERT INTO rating VALUES(8, 61, 5);
INSERT INTO rating VALUES(8, 62, 1);
INSERT INTO rating VALUES(8, 63, 5);
INSERT INTO rating VALUES(8, 66, 1);
INSERT INTO rating VALUES(8, 67, 3);
INSERT INTO rating VALUES(8, 68, 3);
INSERT INTO rating VALUES(8, 69, 5);
INSERT INTO rating VALUES(8, 70, 5);
INSERT INTO rating VALUES(8, 71, 0);
INSERT INTO rating VALUES(8, 72, 1);
INSERT INTO rating VALUES(8, 73, 4);
INSERT INTO rating VALUES(8, 74, 3);
INSERT INTO rating VALUES(8, 75, 3);
INSERT INTO rating VALUES(8, 76, 0);
INSERT INTO rating VALUES(8, 77, 2);
INSERT INTO rating VALUES(8, 78, 0);
INSERT INTO rating VALUES(8, 79, 2);
INSERT INTO rating VALUES(8, 80, 1);
INSERT INTO rating VALUES(8, 81, 5);
INSERT INTO rating VALUES(8, 82, 2);
INSERT INTO rating VALUES(8, 83, 1);
INSERT INTO rating VALUES(8, 84, 3);
INSERT INTO rating VALUES(8, 85, 2);
INSERT INTO rating VALUES(8, 86, 1);
INSERT INTO rating VALUES(8, 87, 1);
INSERT INTO rating VALUES(8, 88, 4);
INSERT INTO rating VALUES(8, 89, 5);
INSERT INTO rating VALUES(8, 90, 1);
INSERT INTO rating VALUES(8, 91, 5);
INSERT INTO rating VALUES(8, 92, 4);
INSERT INTO rating VALUES(8, 93, 5);
INSERT INTO rating VALUES(8, 94, 2);
INSERT INTO rating VALUES(8, 95, 0);
INSERT INTO rating VALUES(8, 96, 5);
INSERT INTO rating VALUES(8, 97, 0);
INSERT INTO rating VALUES(8, 99, 3);
INSERT INTO rating VALUES(8, 100, 4);
INSERT INTO rating VALUES(9, 1, 5);
INSERT INTO rating VALUES(9, 2, 0);
INSERT INTO rating VALUES(9, 3, 2);
INSERT INTO rating VALUES(9, 4, 4);
INSERT INTO rating VALUES(9, 5, 2);
INSERT INTO rating VALUES(9, 6, 4);
INSERT INTO rating VALUES(9, 7, 3);
INSERT INTO rating VALUES(9, 8, 3);
INSERT INTO rating VALUES(9, 9, 3);
INSERT INTO rating VALUES(9, 10, 1);
INSERT INTO rating VALUES(9, 11, 0);
INSERT INTO rating VALUES(9, 12, 0);
INSERT INTO rating VALUES(9, 13, 4);
INSERT INTO rating VALUES(9, 14, 5);
INSERT INTO rating VALUES(9, 15, 4);
INSERT INTO rating VALUES(9, 16, 1);
INSERT INTO rating VALUES(9, 17, 2);
INSERT INTO rating VALUES(9, 18, 4);
INSERT INTO rating VALUES(9, 19, 2);
INSERT INTO rating VALUES(9, 20, 0);
INSERT INTO rating VALUES(9, 21, 1);
INSERT INTO rating VALUES(9, 22, 4);
INSERT INTO rating VALUES(9, 23, 0);
INSERT INTO rating VALUES(9, 24, 2);
INSERT INTO rating VALUES(9, 25, 4);
INSERT INTO rating VALUES(9, 26, 5);
INSERT INTO rating VALUES(9, 27, 1);
INSERT INTO rating VALUES(9, 28, 4);
INSERT INTO rating VALUES(9, 29, 1);
INSERT INTO rating VALUES(9, 30, 0);
INSERT INTO rating VALUES(9, 31, 4);
INSERT INTO rating VALUES(9, 32, 3);
INSERT INTO rating VALUES(9, 33, 2);
INSERT INTO rating VALUES(9, 34, 0);
INSERT INTO rating VALUES(9, 35, 1);
INSERT INTO rating VALUES(9, 36, 3);
INSERT INTO rating VALUES(9, 37, 3);
INSERT INTO rating VALUES(9, 38, 5);
INSERT INTO rating VALUES(9, 39, 4);
INSERT INTO rating VALUES(9, 40, 5);
INSERT INTO rating VALUES(9, 41, 5);
INSERT INTO rating VALUES(9, 42, 4);
INSERT INTO rating VALUES(9, 43, 4);
INSERT INTO rating VALUES(9, 44, 5);
INSERT INTO rating VALUES(9, 45, 2);
INSERT INTO rating VALUES(9, 46, 5);
INSERT INTO rating VALUES(9, 47, 4);
INSERT INTO rating VALUES(9, 48, 2);
INSERT INTO rating VALUES(9, 49, 2);
INSERT INTO rating VALUES(9, 50, 5);
INSERT INTO rating VALUES(9, 51, 0);
INSERT INTO rating VALUES(9, 52, 1);
INSERT INTO rating VALUES(9, 53, 3);
INSERT INTO rating VALUES(9, 54, 2);
INSERT INTO rating VALUES(9, 55, 2);
INSERT INTO rating VALUES(9, 56, 0);
INSERT INTO rating VALUES(9, 57, 0);
INSERT INTO rating VALUES(9, 58, 5);
INSERT INTO rating VALUES(9, 59, 1);
INSERT INTO rating VALUES(9, 60, 3);
INSERT INTO rating VALUES(9, 61, 2);
INSERT INTO rating VALUES(9, 62, 4);
INSERT INTO rating VALUES(9, 63, 4);
INSERT INTO rating VALUES(9, 66, 4);
INSERT INTO rating VALUES(9, 67, 1);
INSERT INTO rating VALUES(9, 68, 2);
INSERT INTO rating VALUES(9, 69, 2);
INSERT INTO rating VALUES(9, 70, 0);
INSERT INTO rating VALUES(9, 71, 3);
INSERT INTO rating VALUES(9, 72, 2);
INSERT INTO rating VALUES(9, 73, 4);
INSERT INTO rating VALUES(9, 74, 4);
INSERT INTO rating VALUES(9, 75, 5);
INSERT INTO rating VALUES(9, 76, 1);
INSERT INTO rating VALUES(9, 77, 2);
INSERT INTO rating VALUES(9, 78, 0);
INSERT INTO rating VALUES(9, 79, 5);
INSERT INTO rating VALUES(9, 80, 4);
INSERT INTO rating VALUES(9, 81, 5);
INSERT INTO rating VALUES(9, 82, 4);
INSERT INTO rating VALUES(9, 83, 5);
INSERT INTO rating VALUES(9, 84, 0);
INSERT INTO rating VALUES(9, 85, 4);
INSERT INTO rating VALUES(9, 86, 5);
INSERT INTO rating VALUES(9, 87, 2);
INSERT INTO rating VALUES(9, 88, 2);
INSERT INTO rating VALUES(9, 89, 1);
INSERT INTO rating VALUES(9, 90, 5);
INSERT INTO rating VALUES(9, 91, 3);
INSERT INTO rating VALUES(9, 92, 1);
INSERT INTO rating VALUES(9, 93, 3);
INSERT INTO rating VALUES(9, 94, 4);
INSERT INTO rating VALUES(9, 95, 0);
INSERT INTO rating VALUES(9, 96, 2);
INSERT INTO rating VALUES(9, 97, 4);
INSERT INTO rating VALUES(9, 99, 5);
INSERT INTO rating VALUES(9, 100, 3);
